// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEovGBkiKsQX3HIN5IeXn_TjPAv4JclwI',
    appId: '1:439373088037:web:c789a4ef4c5b8651d0c6cc',
    messagingSenderId: '439373088037',
    projectId: 'bitki-tanima-mobil',
    authDomain: 'bitki-tanima-mobil.firebaseapp.com',
    storageBucket: 'bitki-tanima-mobil.firebasestorage.app',
    measurementId: 'G-SMJGP9WEMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTO_9zsOZ0aYvHuQBjirmortQpFvQ4S_E',
    appId: '1:439373088037:android:aa75aeacba6f3dd1d0c6cc',
    messagingSenderId: '439373088037',
    projectId: 'bitki-tanima-mobil',
    storageBucket: 'bitki-tanima-mobil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPVLgBAuXTkb6Q-ghzoLTIrIVwgjKVlQ',
    appId: '1:439373088037:ios:d29d33c98c03329ad0c6cc',
    messagingSenderId: '439373088037',
    projectId: 'bitki-tanima-mobil',
    storageBucket: 'bitki-tanima-mobil.firebasestorage.app',
    iosBundleId: 'com.example.bitkiTanimaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQPVLgBAuXTkb6Q-ghzoLTIrIVwgjKVlQ',
    appId: '1:439373088037:ios:d29d33c98c03329ad0c6cc',
    messagingSenderId: '439373088037',
    projectId: 'bitki-tanima-mobil',
    storageBucket: 'bitki-tanima-mobil.firebasestorage.app',
    iosBundleId: 'com.example.bitkiTanimaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEovGBkiKsQX3HIN5IeXn_TjPAv4JclwI',
    appId: '1:439373088037:web:56bac39ebaf84202d0c6cc',
    messagingSenderId: '439373088037',
    projectId: 'bitki-tanima-mobil',
    authDomain: 'bitki-tanima-mobil.firebaseapp.com',
    storageBucket: 'bitki-tanima-mobil.firebasestorage.app',
    measurementId: 'G-CGKZSHN71W',
  );
}
